尋找人臉

In [ ]:
import dlib
import cv2
import imutils
# 讀取照片圖檔
img = cv2.imread('r6.jpg')

# 縮小圖片
img = imutils.resize(img, width=1280)

# Dlib 的人臉偵測器
detector = dlib.get_frontal_face_detector()  #預測灰化後的圖像，評估有幾張臉在這張圖像中

# 偵測人臉
# 參數1表示我們對圖像進行向上采樣1倍，這將使一切變的更大
# 進而讓我們檢測出更多的人臉
face_rects = detector(img, 1)
facs_all=len(face_rects)
print(f'Number of faces detected: {facs_all}')
print('face_rects',face_rects)
# 取出所有偵測的結果
for i, d in enumerate(face_rects):
    x1 = d.left()
    y1 = d.top()
    x2 = d.right()
    y2 = d.bottom()

  # 以方框標示偵測的人臉
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 4, cv2.LINE_AA)

# 顯示結果
cv2.imshow("Face Detection", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

Number of faces detected: 2
face_rects <dlib.dlib.rectangles object at 0x000002822C557C30>


第二種尋找人臉

In [ ]:
import dlib
import cv2
import imutils

img = cv2.imread('r6.jpg')#lebron.pngNBA.jpg
img = imutils.resize(img, width=1280)
detector = dlib.get_frontal_face_detector()

# 偵測人臉，輸出分數
face_rects, scores, idx = detector.run(img, 0, -1)

for i, d in enumerate(face_rects):
    x1 = d.left()
    y1 = d.top()
    x2 = d.right()
    y2 = d.bottom()
    text = "%2.2f(%d)" % (scores[i], idx[i])

    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 4, cv2.LINE_AA)

  # 標示分數
    cv2.putText(img, text, (x1, y1), cv2.FONT_HERSHEY_DUPLEX,
          0.7, (255, 255, 255), 1, cv2.LINE_AA)

cv2.imshow("Face Detection", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

即時串流影像人臉偵測

In [ ]:
import dlib
import cv2
import imutils

# 開啟影片檔案
cap = cv2.VideoCapture(0)

# Dlib 的人臉偵測器
detector = dlib.get_frontal_face_detector()

#print(f'Number of faces detected: {}'.format(len(dets)))
# 以迴圈從影片檔案讀取影格，並顯示出來
while(cap.isOpened()):
    ret, frame = cap.read()

  # 偵測人臉
    face_rects, scores, idx = detector.run(frame, 0)

  # 取出所有偵測的結果
    for i, d in enumerate(face_rects):
        x1 = d.left()
        y1 = d.top()
        x2 = d.right()
        y2 = d.bottom()
        text = "%2.2f(%d)" % (scores[i], idx[i])

        # 以方框標示偵測的人臉
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 4, cv2.LINE_AA)

        # 標示分數
        cv2.putText(frame, text, (x1, y1), cv2.FONT_HERSHEY_DUPLEX,0.7, (255, 255, 255), 1, cv2.LINE_AA)

  # 顯示結果
    cv2.imshow("Face Detection", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

影片人臉偵測

In [ ]:
import dlib
import cv2
import imutils

# 開啟影片檔案
cap = cv2.VideoCapture('video.mp4')

# 取得畫面尺寸
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# 使用 XVID 編碼
fourcc = cv2.VideoWriter_fourcc(*'XVID')

# 建立 VideoWriter 物件，輸出影片至 output.avi，FPS 值為 20.0
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (width, height))

# Dlib 的人臉偵測器
detector = dlib.get_frontal_face_detector()

# 以迴圈從影片檔案讀取影格，並顯示出來
while(cap.isOpened()):
    ret, frame = cap.read()

  # 偵測人臉
    face_rects, scores, idx = detector.run(frame, 0)

  # 取出所有偵測的結果
    for i, d in enumerate(face_rects):
        x1 = d.left()
        y1 = d.top()
        x2 = d.right()
        y2 = d.bottom()
        text = "%2.2f(%d)" % (scores[i], idx[i])

    # 以方框標示偵測的人臉
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 4, cv2.LINE_AA)

    # 標示分數
        cv2.putText(frame, text, (x1, y1), cv2.FONT_HERSHEY_DUPLEX,0.7, (255, 255, 255), 1, cv2.LINE_AA)

  # 寫入影格
    out.write(frame)

  # 顯示結果
    cv2.imshow("Face Detection", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
out.release()
cv2.destroyAllWindows()

人臉偵測68點

In [1]:
import dlib
import cv2
import imutils

#選擇第一隻攝影機
cap = cv2.VideoCapture( 0)
#調整預設影像大小，預設值很大，很吃效能
cap.set(cv2. CAP_PROP_FRAME_WIDTH, 650)
cap.set(cv2. CAP_PROP_FRAME_HEIGHT, 500)

#取得預設的臉部偵測器
detector = dlib.get_frontal_face_detector()
#根據shape_predictor方法載入68個特徵點模型，此方法為人臉表情識別的偵測器
predictor = dlib.shape_predictor('C:/Users/Richard/shape_predictor_68_face_landmarks.dat')
  #當攝影機打開時，對每個frame進行偵測
while(cap.isOpened()):
    #讀出frame資訊
    ret, frame = cap.read()

    #偵測人臉
    face_rects, scores, idx = detector.run(frame, 0)

    #取出偵測的結果
    for i, d in enumerate(face_rects):
        x1 = d.left()
        y1 = d.top()
        x2 = d.right()
        y2 = d.bottom()
        text = " %2.2f ( %d )" % (scores[i], idx[i])

      #繪製出偵測人臉的矩形範圍
        cv2.rectangle(frame, (x1, y1), (x2, y2), ( 0, 255, 0), 4, cv2. LINE_AA)

      #標上人臉偵測分數與人臉方向子偵測器編號
        cv2.putText(frame, text, (x1, y1), cv2. FONT_HERSHEY_DUPLEX,0.7, ( 255, 255, 255), 1, cv2. LINE_AA)
 
      #給68特徵點辨識取得一個轉換顏色的frame
        landmarks_frame = cv2.cvtColor(frame, cv2. COLOR_BGR2RGB)

      #找出特徵點位置
        shape = predictor(landmarks_frame, d)
 
      #繪製68個特徵點
        for i in range(68):
            cv2.circle(frame,(shape.part(i).x,shape.part(i).y), 3,( 0, 0, 255), 2)
            cv2.putText(frame, str(i),(shape.part(i).x,shape.part(i).y),cv2. FONT_HERSHEY_COMPLEX, 0.5,( 255, 0, 0), 1)
    #輸出到畫面
    cv2.imshow( "Face Detection", frame)

    #如果按下ESC键，就退出
    if cv2.waitKey( 10) == 27:
        break
#釋放記憶體
cap.release()
#關閉所有視窗
cv2.destroyAllWindows()

KeyboardInterrupt: 

https://www.itread01.com/content/1547209506.html
https://blog.gtwang.org/programming/opencv-webcam-video-capture-and-file-write-tutorial/
https://www.tpisoftware.com/tpu/articleDetails/950
https://www.itread01.com/content/1536326533.html

In [ ]:
import numpy as np
import cv2                #影象處理庫OpenCV
import dlib               #人臉識別庫dlib
#dlib預測器
detector = dlib.get_frontal_face_detector()    #使用dlib庫提供的人臉提取器
predictor = dlib.shape_predictor(r'C:\Users\Richard\shape_predictor_68_face_landmarks.dat')   #構建特徵提取器
#where='C:\\Users\\Richard\\Desktop\\人臉辨識專案\\自練\\facebase\\harden.jpg'
# cv2讀取影象
img = cv2.imread(r'C:\Users\Richard\Desktop\facebase\harden.jpg')

# 取灰度
img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

# 人臉數rects
rects = detector(img_gray, 0)
for i in range(len(rects)):
    landmarks = np.matrix([[p.x, p.y] for p in predictor(img,rects[i]).parts()])  #人臉關鍵點識別
    for idx, point in enumerate(landmarks):        #enumerate函式遍歷序列中的元素及它們的下標
        # 68點的座標
        pos = (point[0, 0], point[0, 1])
        print(idx,pos)

        # 利用cv2.circle給每個特徵點畫一個圈，共68個
        cv2.circle(img, pos, 5, color=(0, 255, 0))
        # 利用cv2.putText輸出1-68
        font = cv2.FONT_HERSHEY_SIMPLEX
        #各引數依次是：圖片，新增的文字，座標，字型，字型大小，顏色，字型粗細
        cv2.putText(img, str(idx+1), pos, font, 0.1, (0, 0, 255), 1,cv2.LINE_AA)

cv2.namedWindow("img", 2)     
cv2.imshow("img", img)       #顯示影象
cv2.waitKey(0)        #等待按鍵，隨後退出

0 (61, 94)
1 (61, 106)
2 (62, 118)
3 (64, 130)
4 (69, 142)
5 (76, 152)
6 (86, 161)
7 (96, 167)
8 (109, 169)
9 (121, 167)
10 (132, 161)
11 (142, 153)
12 (149, 143)
13 (154, 132)
14 (156, 120)
15 (157, 108)
16 (157, 96)
17 (70, 79)
18 (74, 69)
19 (83, 64)
20 (93, 64)
21 (101, 68)
22 (118, 68)
23 (127, 64)
24 (136, 65)
25 (145, 70)
26 (149, 79)
27 (109, 82)
28 (109, 89)
29 (109, 96)
30 (109, 104)
31 (97, 111)
32 (103, 113)
33 (109, 114)
34 (115, 113)
35 (120, 112)
36 (80, 87)
37 (85, 83)
38 (92, 82)
39 (98, 87)
40 (92, 88)
41 (85, 88)
42 (121, 88)
43 (128, 83)
44 (134, 83)
45 (139, 88)
46 (134, 89)
47 (128, 89)
48 (89, 134)
49 (95, 126)
50 (103, 123)
51 (108, 124)
52 (114, 123)
53 (122, 127)
54 (129, 135)
55 (122, 143)
56 (114, 145)
57 (108, 146)
58 (103, 145)
59 (95, 142)
60 (93, 133)
61 (103, 130)
62 (108, 131)
63 (114, 131)
64 (125, 134)
65 (114, 137)
66 (108, 137)
67 (103, 136)


人臉辨識68點實作(http://mahaljsp.asuscomm.com/index.php/2019/06/14/python_face_match/)
https://allen108108.github.io/blog/2020/04/16/%E4%BA%BA%E8%87%89%E8%BE%A8%E8%AD%98%E7%B3%BB%E7%B5%B1%20Face%20Recognition%20%E9%96%8B%E7%99%BC%E7%B4%80%E9%8C%84%20%20(%20OpenCV%20_%20Dlib%20)/

In [ ]:
import sys, os, dlib, glob, numpy
from skimage import io
import cv2
import imutils

#if len(sys.argv) != 2:
#    print("請輸入要辨識的圖片檔名")
#    exit()

# 依據臉部68個特徵預測臉型, 臉面偵測模型
path_face_landmarks_pattern = "C:/Users/Richard/shape_predictor_68_face_landmarks.dat"

# 人臉辨識模型
path_face_recognition_pattern = "C:/Users/Richard/dlib_face_recognition_resnet_model_v1.dat"

# 人臉資料庫路徑
path_face_database = "facebase"

# 要辨識的圖片檔名
#path_img = sys.argv[1]

# 載入臉型檢測器
detector_face_shape = dlib.get_frontal_face_detector()

# 載入人臉特徵點檢測器
detector_face_landmarks = dlib.shape_predictor(path_face_landmarks_pattern)

# 載入人臉辨識檢測器
detector_face_recognition= dlib.face_recognition_model_v1(path_face_recognition_pattern)

# 比對人臉描述子列表
descriptors = []

# 比對人臉名稱列表
candidate = []

# 針對比對資料夾裡每張圖片做比對:
# 1.人臉偵測
# 2.特徵點偵測
# 3.取得描述子
for f in glob.glob(os.path.join(path_face_database , "*.jpg" )):   
    osPath = os.path.basename(f) #去除路徑, 只顯示檔案名稱
    candidate.append(os.path.splitext(osPath)[0])#splittext將檔名及副檔名切開
    img = io.imread(f) #將資料庫裏的圖片一張一張載入
    #人臉偵測
    face_shape = detector_face_shape(img, 2)
    facs_all=len(face_shape)
    print(f'Number of faces detected: {facs_all}')
    for k, d in enumerate(face_shape):
        #特徵點偵測
        face_landmarks = detector_face_landmarks(img, d)

        #取得描述子，128維特徵向量
        face_descriptor = detector_face_recognition.compute_face_descriptor(img, face_landmarks)

        #轉換numpy array格式
        v = numpy.array(face_descriptor)
        descriptors.append(v)
dist = []
for k, d in enumerate(face_shape):
    #k是第幾組的意思, 由0開始, d是臉型在圖片的左上角及右下角, 如 d: [(153,67) (282,196)]
    face_landmarks = detector_face_landmarks(img, d)
    face_descriptor = detector_face_recognition.compute_face_descriptor(img, face_landmarks)
    d_test = numpy.array(face_descriptor)

    x1 = d.left()
    y1 = d.top()
    x2 = d.right()
    y2 = d.bottom()
    # 以方框標示偵測的人臉
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 4, cv2.LINE_AA)
     # 計算歐式距離
    for i in descriptors:
        dist_ = numpy.linalg.norm(i - d_test)
        dist.append(dist_)

# 將比對人名和比對出來的歐式距離組成一個dict
    c_d = dict(zip(candidate, dist))

# 根據歐式距離由小到大排序
    cd_sorted = sorted(c_d.items(), key=lambda d: d[1])
# 取得最短距離就為辨識出的人名
    rec_name = cd_sorted[0][0]

# 將辨識出的人名印到圖片上面
#各引數依次是：圖片，新增的文字，座標，字型，字型大小，顏色，字型粗細
    cv2.putText(img, rec_name, (x1, y2), cv2.FONT_HERSHEY_SIMPLEX, 1, (100, 255, 255), 2, cv2.LINE_AA)

    img = imutils.resize(img, width=600)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    cv2.imshow("Face Recognition", img)
# 隨意Key一鍵結束程式
cv2.waitKey(0)
cv2.destroyAllWindows()



Number of faces detected: 1
Number of faces detected: 1
Number of faces detected: 1
Number of faces detected: 1
Number of faces detected: 1
[[[ 4  3  5]
  [ 4  3  5]
  [ 4  3  5]
  ...
  [ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]]

 [[ 4  3  5]
  [ 4  3  5]
  [ 4  3  5]
  ...
  [ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]]

 [[ 4  3  5]
  [ 4  3  5]
  [ 4  3  5]
  ...
  [ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]]

 ...

 [[32 32 38]
  [32 32 38]
  [30 30 36]
  ...
  [13 10 25]
  [16 14 28]
  [16 14 28]]

 [[32 32 38]
  [32 32 38]
  [30 30 36]
  ...
  [14 11 26]
  [18 15 30]
  [18 15 30]]

 [[32 32 38]
  [32 32 38]
  [30 30 36]
  ...
  [14 11 26]
  [18 15 30]
  [18 15 30]]]
